version: "3.8"
services:
  database:
    restart: unless-stopped
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-persistent:/var/lib/mysql
    networks:
      - ramJackApp

  php:
    build: .
    expose:
      - 9000
    container_name: php_container
    volumes:
      - ./src:/var/www/html
      - .env:/var/www/html/.env
    networks:
      - ramJackApp
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
      php-fpm"

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src:/var/www/html
    ports:
      - 5001:80
    depends_on:
      - php
    networks:
      - ramJackApp

  store:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - redis-persistent:/data
    networks:
      - ramJackApp

volumes:
  redis-persistent:
  mysql-persistent:

networks:
  ramJackApp:
    driver: bridge
