name: Docker Image CI/CD for GHCR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username tlud2192 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build -t ghcr.io/federalnexusinc/laravel-docker:latest .
          docker push ghcr.io/federalnexusinc/laravel-docker:latest